local Vector = require "vector"

local physics = {}

function physics.load()

    love.physics.setMeter(64) --the height of a meter our worlds will be 64px
    world = love.physics.newWorld(0, 9.81*64, true) --create a world for the bodies to exist in with horizontal gravity of 0 and vertical gravity of 9.81
    objects = {} -- table to hold all our physical objects

end

function physics.addRectangularObject(args)
	local object = {}
	object.body = love.physics.newBody(world,args.position[1],args.position[2],args.bodyType)
	object.shape = love.physics.newRectangleShape(args.size[1],args.size[2])
	object.fixture = love.physics.newFixture(object.body,object.shape,args.density)
	objects[#objects+1] = object
end

function physics.addCircularObject(args)
	local object = {}
	object.body = love.physics.newBody(world,args.position[1],args.position[2],args.bodyType)
	object.shape = love.physics.newCircleShape(args.radius)
	object.fixture = love.physics.newFixture(object.body,object.shape,args.density)
	objects[#objects+1] = object
end

function physics.update(dt)

    if inGame == true and inGameMenu == false then
        world:update(dt) --this puts the world into motion
     
        --here we are going to create some keyboard events
        if love.keyboard.isDown("d") then --press the d key to push the ball to the right
            objects.ball.body:applyForce(400, 0)
        elseif love.keyboard.isDown("a") then --press the a key to push the ball to the left
            objects.ball.body:applyForce(-400, 0)
        elseif love.keyboard.isDown("space") then --press the space key to set the ball in the air
            objects.ball.body:setPosition(650/2, 650/2)
            objects.ball.body:setLinearVelocity(0, 0) --we must set the velocity to zero to prevent a potentially large velocity generated by the change in position
        end
    end

end

return physics