local physics = {}

function physics.load()

    love.physics.setMeter(64) --the height of a meter our worlds will be 64px
    world = love.physics.newWorld(0, 9.81*64, true) --create a world for the bodies to exist in with horizontal gravity of 0 and vertical gravity of 9.81
    objects = {} -- table to hold all our physical objects

end

function physics.update(dt)

    if inGame == true then
        world:update(dt) --this puts the world into motion
     
        --here we are going to create some keyboard events
        if love.keyboard.isDown("right") then --press the right arrow key to push the ball to the right
            objects.ball.body:applyForce(400, 0)
        elseif love.keyboard.isDown("left") then --press the left arrow key to push the ball to the left
            objects.ball.body:applyForce(-400, 0)
        elseif love.keyboard.isDown("up") then --press the up arrow key to set the ball in the air
            objects.ball.body:setPosition(650/2, 650/2)
            objects.ball.body:setLinearVelocity(0, 0) --we must set the velocity to zero to prevent a potentially large velocity generated by the change in position
        end
    end

end

return physics