local Vector = require "vector"
local objects = require "objects"
local images = require "images"
local ui = require "ui"

local player = {}

function player.load()

	objects.add({worldNum=currentWorld,stats={health=100},recolorUnderwater=true,position=Vector(300,200),shape={type="rectangle",size=Vector(20,60)},density=1,bodyType="dynamic",drawing={type="image",image=images.player}})
    objects[1].body:setFixedRotation(true)
    worldChanged = false

end

function player.land()

    local playerObject = objects[1]
    local currentWorldObjects = objects.getObjectsByWorld(currentWorld)
    playerObject.worldNum = currentWorld
    playerObject.body:setY(currentWorldObjects[math.floor(#currentWorldObjects/2)].body:getY()-150) --Moves player to surface
    playerObject.body:setActive(true)

end

function player.die()

    ui.setPage("deathScreen")

end

function player.update(dt)

    local playerObject = objects[1]
    local currentWorldObjects = objects.getObjectsByWorld(currentWorld)

	if love.keyboard.isDown("d") then --press the d key to push to the right
        playerObject.body:applyForce(400, 0)
    end
    if love.keyboard.isDown("a") then --press the a key to push to the left
        playerObject.body:applyForce(-400, 0)
    end
    if love.keyboard.isDown("w") or love.keyboard.isDown("space") then
        playerObject.body:applyForce(0, -500)
    end
    if love.keyboard.isDown("s") then
        playerObject.body:applyForce(0, 400)
    end
    if love.keyboard.isDown("return") and worldChanged == false then --press the enter key to set in the air
        planets.changeWorld(math.random(1,numWorlds))
        player.land()
        playerObject.body:setPosition(650/2, 650/2)
        playerObject.body:setLinearVelocity(0, 0) --we must set the velocity to zero to prevent a potentially large velocity generated by the change in position
        worldChanged = true
    elseif love.keyboard.isDown("return") == false then
    	worldChanged = false
    end

    if playerObject.body:getY() >= currentWorldObjects[math.floor(#currentWorldObjects/2)].body:getY() then
       playerObject.body:applyForce(0, -100)
    end

    if playerObject.body:getX() < -25000 or playerObject.body:getX() > 25000 then
       playerObject.stats.health = playerObject.stats.health - 1
    end

    if playerObject.stats.health <= 0 then
        player.die()
    end

end

return player